name = "ScoringRules"
uuid = "4513502d-b6e3-4a45-a349-870a0c92fe5c"
authors = ["Joshua C. Macdonald <jmacdo16@jh.edu>"]
version = "0.1.0"

[deps]

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
